### ISSUE TITLE
Local Prettier < 1.8.0 throws prettierInstance.getSupportInfo is not a function

### ISSUE THREAD

**Issue by JHilker** [prettier/prettier-vscode#710]
Connected to issues: https://github.com/prettier/prettier-vscode/issues/704 https://github.com/prettier/prettier-vscode/issues/705

Connected to PR: https://github.com/prettier/prettier-vscode/pull/706

Currently running version >=1.8.1 of `prettier-vscode` throws `prettierInstance.getSupportInfo is not a function` when run with a local version of Prettier < 1.8.0. This is due to a switch in #706 to use the local version of Prettier to determine the valid parsers, due to an upstream issue in Prettier where `getSupportInfo` returns the wrong information regarding the babel/babylon parser: https://github.com/prettier/prettier/issues/5822

## Workaround:

Either:
* Upgrade your local version of Prettier to be >= 1.8.0
* Downgrade prettier-vscode to 1.7.3

**Comment by ymulenll** [comment]
@JHilker I am having the same issue, using Prettier v1.8.1

**Comment by martellaj** [comment]
@JHilker Unsure if it's the **same** issue (happy to help diagnose), but prettier-vscode (latest) isn't working on VS Code Insiders (1.33.0-insider). I confirmed that the extension still works on the latest production VS Code (1.32.3).

**Comment by CiGit** [comment]
Fixed !
