### ISSUE TITLE
Getting `Cannot find module 'typescript'` after update to 1.7.0

### ISSUE THREAD

**Issue by pikax** [prettier/prettier-vscode#620]
After update to 1.7.0 prettier stopped working and I'm getting the error
```
11/7/2018, 2:24:06 PM:
----------------------
Cannot find module 'typescript'
```
I'm using typescript@3.1.6, was working before the update.

**Comment by CiGit** [comment]
Can you list what's in `$HOME/.vscode/extensions/esbenp.prettier-vscode-1.7.0/node_modules/prettier`

**Comment by aharvard** [comment]
I'm having the same issue. (But have downgraded for now)

Here is what shows for me:
![screen shot 2018-11-07 at 8 41 09 am](https://user-images.githubusercontent.com/10472610/48138037-077ee400-e269-11e8-9393-4617ce74665f.png)

**Comment by pikax** [comment]
the files are: 
`.vscode\extensions\esbenp.prettier-vscode-1.7.0\node_modules\prettier`
```
bin-prettier.js
index.js
LICENSE
package.json
parser-angular.js
parser-babylon.js
parser-flow.js
parser-glimmer.js
parser-graphql.js
parser-html.js
parser-markdown.js
parser-postcss.js
parser-typescript.js
parser-yaml.js
README.md
standalone.js
third-party.js
```

**Comment by CiGit** [comment]
tslintIntegration or eslintIntegration?

**Comment by pikax** [comment]
tslintIntegration

**Comment by aharvard** [comment]
both are set false in my settings.

**Comment by CiGit** [comment]
I've reproduced it with tslintIntegration true.
Try reinstalling @aharvard. Doesn't seem to be the same

**Comment by aharvard** [comment]
Thanks for the support @CiGit...  I've uninstalled and reinstalled. I've also tried with `tslintIntegration` true/false and `eslintIntegration` true/false. 

no matter the setting, I still get
```
11/7/2018, 8:55:15 AM:
----------------------
Cannot find module 'typescript'
```

**Comment by DevanB** [comment]
Odd, I'm on 1.7.0 and have `tslintIntegration` turned on, `eslintIntegration` turned off, but I'm having no issues. 

I'm happy to help in any way I can.

**Comment by pikax** [comment]
I'm running: 
- node: 10.10.0 
- vscode: 1.28.2
- yarn: 1.9.4
- windows 10 

In `esbenp.prettier-vscode-1.7.0\node_modules`  there's no `typescript` folder

I ran `yarn` in `esbenp.prettier-vscode-1.7.0` and now is working 😕

**Comment by CiGit** [comment]
prettier-tslint needs typescript but we don't bundle it.

**Comment by CiGit** [comment]
Publishing with "typescript" ongoing

**Comment by CiGit** [comment]
@pikax We need `typescript@2` as a peer dependency to prettier-tslint
Seems it also works with a `typescript@3`

Closing. Fixed in 1.7.1

**Comment by aharvard** [comment]
1.7.1 works for me! Thanks for the quick fix @CiGit.

**Comment by aleclarson** [comment]
Hmm, I'm getting this on v1.7.2, and switching to VSCode's TS version instead of the workspace version has revealed that it's the workspace version that's bugging out / missing. I wonder how / why it's not falling back to the TS version that's installed specifically by Prettier...? (or why it's not using it by default)

```sh
# macOS version
$ defaults read loginwindow SystemVersionStampAsString
10.13.6

# VS Code version
$ code --version
1.28.2
7f3ce96ff4729c91352ae6def877e59c561f4850
x64
```

Might not be a bug on your end. Not sure.
