### ISSUE TITLE
v12.1.0 break some plugin

### ISSUE THREAD

**Issue by HerrCai0907** [prettier/prettier-vscode#3907]
### Preflight Checklist

- [x] I have read the [troubleshooting guide](https://github.com/prettier/prettier-vscode/blob/main/docs/troubleshooting.md)
- [x] I have searched [existing issues](https://github.com/prettier/prettier-vscode/issues) and this is not a duplicate
- [x] This is a bug with the **VS Code extension**, not with how Prettier formats code

### Issue Summary

after upgrade to v12.1.0, plugin based on wasm does not work anymore
```
["ERROR" - 08:41:43] WebAssembly.instantiateStreaming is not a function
TypeError: WebAssembly.instantiateStreaming is not a function
	at file:///Users/caicongcong/dev/warpo/node_modules/assemblyscript-prettier/node_modules/assemblyscript/dist/assemblyscript.js:9:38049
```

### Reproduction Repository

https://github.com/wasm-ecosystem/warpo

### Steps to Reproduce

1. clone the repo
2. change some format in assemblyscript/src/...
3. format with plugin

### Expected Behavior

plugin with wasm can be load successfully

### Actual Behavior

error

### Operating System

macOS

### VS Code Version

Version: 1.108.1 Commit: 585eba7c0c34fd6b30faac7c62a42050bfbc0086 Date: 2026-01-14T14:55:44.241Z Electron: 39.2.7 ElectronBuildId: 12953945 Chromium: 142.0.7444.235 Node.js: 22.21.1 V8: 14.2.231.21-electron.0 OS: Darwin arm64 25.2.0

### Prettier Extension Version

v12.1.0

### Prettier Version

3.6.2

### Prettier Extension Logs

```text
["ERROR" - 08:41:43] WebAssembly.instantiateStreaming is not a function
TypeError: WebAssembly.instantiateStreaming is not a function
	at file:///Users/caicongcong/dev/warpo/node_modules/assemblyscript-prettier/node_modules/assemblyscript/dist/assemblyscript.js:9:38049
```

### Prettier Configuration

```json
printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: "as-needed"
jsxSingleQuote: false
trailingComma: "es5"
bracketSpacing: true
arrowParens: "always"
vueIndentScriptAndStyle: false
endOfLine: "lf"
plugins:
  - assemblyscript-prettier
```

**Comment by ntotten** [comment]
@copilot create a reproduction of this issue in our tests then see if you can figure out what the cause is and suggest a fix.

**Comment by danawoodman** [comment]
all versions after 11.0.3 appear broken in Cursor with following error even after restarting extension + cursor. 

this was the same issue that was previously fixed but now is broken again

<img width="529" height="60" alt="Image" src="https://github.com/user-attachments/assets/12d07b74-3099-49f9-a7d1-eba251648d47" />

**Comment by aceHubert** [comment]
> all versions after 11.0.3 appear broken in Cursor with following error even after restarting extension + cursor.
> 
> this was the same issue that was previously fixed but now is broken again
> 
> <img alt="Image" width="529" height="60" src="https://private-user-images.githubusercontent.com/157695/539354539-12d07b74-3099-49f9-a7d1-eba251648d47.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk0MjE1NjksIm5iZiI6MTc2OTQyMTI2OSwicGF0aCI6Ii8xNTc2OTUvNTM5MzU0NTM5LTEyZDA3Yjc0LTMwOTktNDlmOS1hN2QxLWViYTI1MTY0OGQ0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyNlQwOTU0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjE0MjUxNmVmZDg3YTNiZjM0MDQ4MTZkNmUxOTNhZmYzMjk2N2I0ZTk3MmE5ZGI1OTkzNDQxMTc3YTY0NmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Af-kfqZFlEvrnv4IiWk3k6hbPZgXhh_SBZ0EBrNXcKQ">

same error
